version: "2"

run:
  timeout: 5m

linters:
  enable:
    - bodyclose
    - errcheck
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unused

  settings:
    gocyclo:
      min-complexity: 30
